apiVersion: v1
kind: Service
metadata:
  name: neo4j-core-service
  labels:
    app: neo4j
    component: core
spec:
  clusterIP: None 
  ports:
    - port: 7474
      targetPort: 7474
      name: browser
    - port: 6362
      targetPort: 6362
      name: backup
    - port: 7687
      targetPort: 7687
      name: bolt
  selector:
    app: neo4j
    component: core
