version: '3.5'

##############################################################################
#
# yggdrasil:
# - zookeeper, broker, schema_registry, connect, control_center, rest_proxy
# - all are connected to minir
#
##############################################################################
services:

  ####################
  # hadoop zookeeper
  #
  yggdrasil_zookeeper:
    image: confluentinc/cp-zookeeper
    hostname: yggdrasil_zookeeper
    container_name: yggdrasil_zookeeper
    ports:
      - "2181:2181"
    networks:
      - mimir
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000

  ####################
  # kafka brokers
  #
  yggdrasil_broker_1:
    image: confluentinc/cp-enterprise-kafka
    hostname: yggdrasil_broker_1
    container_name: yggdrasil_broker_1
    ports:
      - "29092:9092"
      - "9092:9092"
    depends_on:
      - yggdrasil_zookeeper
    networks:
      - mimir
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://yggdrasil_broker_1:19092,LOCALHOST://localhost:29092,OUTSIDE://${YGGDRASIL_PUBLIC_IP}:9092
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:19092,LOCALHOST://localhost:29092,OUTSIDE://0.0.0.0:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,LOCALHOST:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=2
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_ZOOKEEPER_CONNECT=yggdrasil_zookeeper:2181
      - KAFKA_METRIC_REPORTERS=io.confluent.metrics.reporter.ConfluentMetricsReporter
      - CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS=yggdrasil_broker_1:19092,yggdrasil_broker_2:19093
      - CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT=yggdrasil_zookeeper:2181
      - CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS=2
      - CONFLUENT_METRICS_ENABLE=true
      - CONFLUENT_SUPPORT_CUSTOMER_ID=anonymous

  yggdrasil_broker_2:
    image: confluentinc/cp-enterprise-kafka
    hostname: yggdrasil_broker_2
    container_name: yggdrasil_broker_2
    ports:
      - "29093:9093"
      - "9093:9093"
    depends_on:
      - yggdrasil_zookeeper
    networks:
      - mimir
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://yggdrasil_broker_2:19093,LOCALHOST://localhost:29093,OUTSIDE://${YGGDRASIL_PUBLIC_IP}:9093
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:19093,LOCALHOST://localhost:29093,OUTSIDE://0.0.0.0:9093
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,LOCALHOST:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=2
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_ZOOKEEPER_CONNECT=yggdrasil_zookeeper:2181
      - KAFKA_METRIC_REPORTERS=io.confluent.metrics.reporter.ConfluentMetricsReporter
      - CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS=yggdrasil_broker_1:19092,yggdrasil_broker_2:19093
      - CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT=yggdrasil_zookeeper:2181
      - CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS=2
      - CONFLUENT_METRICS_ENABLE=true
      - CONFLUENT_SUPPORT_CUSTOMER_ID=anonymous

  ####################
  # schema_registry
  #
  yggdrasil_schema_registry:
    image: confluentinc/cp-schema-registry
    hostname: yggdrasil_schema_registry
    container_name: yggdrasil_schema_registry
    ports:
      - "8081:8081"
    depends_on:
      - yggdrasil_zookeeper
      - yggdrasil_broker_1
      - yggdrasil_broker_2
    networks:
      - mimir
    environment:
      - SCHEMA_REGISTRY_HOST_NAME=yggdrasil_schema_registry
      - SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL=yggdrasil_zookeeper:2181

  ####################
  # rest-proxy
  #
  yggdrasil_rest_proxy:
    image: confluentinc/cp-kafka-rest
    hostname: yggdrasil_rest_proxy
    container_name: yggdrasil_rest_proxy
    ports:
      - "8082:8082"
    depends_on:
      - yggdrasil_zookeeper
      - yggdrasil_broker_1
      - yggdrasil_broker_2
      - yggdrasil_schema_registry
    networks:
      - mimir
    environment:
      - KAFKA_REST_BOOTSTRAP_SERVERS=yggdrasil_broker_1:19092,yggdrasil_broker_2:19093
      - KAFKA_REST_HOST_NAME=yggdrasil_rest_proxy
      - KAFKA_REST_ZOOKEEPER_CONNECT=yggdrasil_zookeeper:2181
      - KAFKA_REST_LISTENERS=http://0.0.0.0:8082
      - KAFKA_REST_SCHEMA_REGISTRY_URL=http://yggdrasil_schema_registry:8081

  ####################
  # connect
  #
  yggdrasil_connect:
    image: confluentinc/cp-kafka-connect
    hostname: yggdrasil_connect
    container_name: yggdrasil_connect
    ports:
      - "8083:8083"
    depends_on:
      - yggdrasil_zookeeper
      - yggdrasil_broker_1
      - yggdrasil_broker_2
      - yggdrasil_schema_registry
    networks:
      - mimir
    volumes:
      - ${YGGDRASIL_CONNECT_PLUGINS:-~/yggdrasil/connect/plugins}:/tmp/connect-plugins
    environment:
      - CONNECT_BOOTSTRAP_SERVERS=yggdrasil_broker_1:19092,yggdrasil_broker_2:19093
      - CONNECT_REST_ADVERTISED_HOST_NAME=yggdrasil_connect
      - CONNECT_REST_PORT=8083
      - CONNECT_GROUP_ID=compose-connect-group
      - CONNECT_CONFIG_STORAGE_TOPIC=docker-connect-configs
      - CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR=2
      - CONNECT_OFFSET_FLUSH_INTERVAL_MS=10000
      - CONNECT_OFFSET_STORAGE_TOPIC=docker-connect-offsets
      - CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR=2
      - CONNECT_STATUS_STORAGE_TOPIC=docker-connect-status
      - CONNECT_STATUS_STORAGE_REPLICATION_FACTOR=2
      - CONNECT_KEY_CONVERTER=io.confluent.connect.avro.AvroConverter
      - CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL=http://yggdrasil_schema_registry:8081
      - CONNECT_VALUE_CONVERTER=io.confluent.connect.avro.AvroConverter
      - CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL=http://yggdrasil_schema_registry:8081
      - CONNECT_INTERNAL_KEY_CONVERTER=org.apache.kafka.connect.json.JsonConverter
      - CONNECT_INTERNAL_VALUE_CONVERTER=org.apache.kafka.connect.json.JsonConverter
      - CONNECT_ZOOKEEPER_CONNECT=yggdrasil_zookeeper:2181
      - CONNECT_PLUGIN_PATH=/usr/share/java,/tmp/connect-plugins,/usr/share/confluent-hub-components
      - CONNECT_LOG4J_LOGGERS=org.apache.zookeeper=DEBUG,org.I0Itec.zkclient=DEBUG,org.reflections=ERROR
    command:
      - bash
      - -c
      - |
        confluent-hub install --no-prompt neo4j/kafka-connect-neo4j:1.0.0
        /etc/confluent/docker/run

  ####################
  # control_center
  #
  yggdrasil_control_center:
    image: confluentinc/cp-enterprise-control-center
    hostname: yggdrasil_control_center
    container_name: yggdrasil_control_center
    ports:
      - "9021:9021"
    depends_on:
      - yggdrasil_zookeeper
      - yggdrasil_broker_1
      - yggdrasil_broker_2
      - yggdrasil_schema_registry
      - yggdrasil_connect
    networks:
      - mimir
    environment:
      - CONTROL_CENTER_BOOTSTRAP_SERVERS=yggdrasil_broker_1:19092,yggdrasil_broker_2:19093
      - CONTROL_CENTER_ZOOKEEPER_CONNECT=yggdrasil_zookeeper:2181
      - CONTROL_CENTER_CONNECT_CLUSTER=yggdrasil_connect:8083
      - CONTROL_CENTER_REPLICATION_FACTOR=2
      - CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS=2
      - CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS=2
      - CONFLUENT_METRICS_TOPIC_REPLICATION=2
      - PORT=9021

################################################################################
#
# networks
#
################################################################################
networks:
  mimir:
    name: mimir
