version: '3.5'

services:

  apollo-server:
    build: ./api
    hostname: apollo-server
    container_name: apollo-server
    ports:
      - 4000:4000
    networks:
      - frontend
      - backend

  apollo-client:
    build: ./ui
    hostname: apollo-client
    container_name: apollo-client
    ports:
      - 3000:3000
    networks:
      - frontend

networks:
  frontend:
    name: frontend
  backend:
    name: backend